# Generated by Django 5.2.5 on 2025-08-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
        ('tickets', '0003_ticket_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='tickets.ticket'),
        ),
    ]
